### PR TITLE
Submit Week Three Challenges

### PR DESCRIPTION
**Pull request by dxania**

### CODE REVIEW

**Comment by Tushcathy** [comment]
Hello, great Job! thanks for trying out the challenges.
here is some feedback on the work done.
1. On the first question,consider making the print statement clearer,  it shows values for the whole array and the second one, but just by looking one can't easily tell which is the mean, std or variance. 
2.Number two, the array was reshaped into a one row array instead of one column.(interchange the 6 and 1 in the reshape function)
3.question three, the rounding off can be got with round(average,2)
4.Everything else is perfect.

**Review by dxania — COMMENTED** [review]
@Tushcathy please find here an implementation of the feedback received:

- [x] 1. Clear output (mean, standard deviation, variance)
- [x] 2. One column array

> round(average, 2) did not work. I had initially tried it as seen in the #commented code

**Comment by Tushcathy** [comment]
What version of python are you using? Perhaps round behaves different on your machine. I have copied your code and run it, it works just fine on my pc.
So you can remove your comments and the code will be merged.

**Review by dxania — COMMENTED** [review]
Comments removed
Thanks @Tushcathy

**Pull request merged**
