### PR TITLE
Answers to week three challenges

### PR DESCRIPTION
**Pull request by KarungiAnna**

### CODE REVIEW

**Comment by evananyonga** [comment]
Anna, I think for number 2, the best course of action would've been to print the shape of the array, not the array itself.

**Comment by Tushcathy** [comment]
Hello, Thanks for attempting to do exercises, before the work can be merged, you will need to answer all the questions. You can reach out on the whatsapp group incase you get stuck.

**Comment by KarungiAnna** [comment]
Hi. I have been able to work on it.

**Comment by Tushcathy** [comment]
Awesome,
for the last two numbers, all that was required was the calculation.(You're right to use plots too, the show the relationship easily, but graphs were out of scope for that week's work.)

**Comment by KarungiAnna** [comment]
Hi. I have been able to remove the graphs on the last two numbers.

**Comment by Tushcathy** [comment]
Great thank you. You work will now be merged.

**Pull request closed without merging**
